#!/bin/sh

lupdate -verbose \
  App.cpp \
  CountLoopWnd/CountLoopWnd.ui \
  DecSpeedWnd/DecSpeedWnd_MainWnd.cpp \
  IncSpeedWnd/IncSpeedWnd.ui \
  LimitSettingWnd/LimitSettingWnd.ui \
  MainWnd/ABLoopPosWnd.cpp \
  MainWnd/ABLoopPosWnd.ui \
  MainWnd/AllSaveWnd.ui \
  MainWnd/AllSaveWnd_MainWnd.cpp \
  MainWnd/ChorusCustomizeWnd.ui \
  MainWnd/CompressorCustomizeWnd.ui \
  MainWnd/DelayCustomizeWnd.ui \
  MainWnd/DistortionCustomizeWnd.ui \
  MainWnd/Explorer.cpp \
  MainWnd/FlangerCustomizeWnd.ui \
  MainWnd/GargleCustomizeWnd.ui \
  MainWnd/LAMECommandLineWnd.ui \
  MainWnd/MainWnd.cpp \
  MainWnd/MainWnd.ui \
  MainWnd/Menu_MainWnd.cpp \
  MainWnd/OpenURLWnd.cpp \
  MainWnd/OpenURLWnd.ui \
  MainWnd/PlayListView_MainWnd.cpp \
  MainWnd/PlayPositionWnd.ui \
  MainWnd/PlayRangeWnd.ui \
  MainWnd/PreferencesWnd.cpp \
  MainWnd/PreferencesWnd.ui \
  MainWnd/PresetNameInputWnd.ui \
  MainWnd/RMenu_Explorer.cpp \
  MainWnd/RMenu_ListView.cpp \
  MainWnd/Reverb3DCustomizeWnd.ui \
  MainWnd/ReverbCustomizeWnd.ui \
  MainWnd/Sound.cpp \
  MainWnd/Tab_MainWnd.cpp \
  MetronomeWnd/MetronomeWnd.ui \
  TimerPlayWnd/TimerPlayWnd.ui \
  -ts Hayaemon_ja.ts
